'use client'
import './globals.css'
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
import Nav from '../../components/NavBar'
import Footer from '../../components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Pato a Jato',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <link rel="shortcut icon" href="/favicon.ico" /> */}
     <link rel="icon" href="favicon.ico" />
     {/* <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="theme-color" content="#000000" /> */}
      <body className={inter.className}>{children}
      {/* <Nav/>      

      <Footer/> */}
      </body>
    </html>
  )
}


